HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html> 
  <head>
    <title>MIL DISCULPAS</title>
  </head> 
  <body>
    <div> 
          <h2 >MIL DISCULPAS!!! ESTAREMOS EN LÍNEA CUANTO ANTES</h2>
    </div>
  </body> 
</html>